# Unofficial codex-mcp installer for Windows PowerShell
#   irm https://raw.githubusercontent.com/zai-one/codex-mcp/main/scripts/install.ps1 | iex
param(
  [string]$Project = "$env:USERPROFILE",
  [string]$HomeDir = "$env:LOCALAPPDATA\codex-mcp"
)

$ErrorActionPreference = "Stop"
Write-Host "Unofficial codex-mcp installer (not OpenAI/Codex official)" -ForegroundColor Yellow

if (-not (Get-Command git -ErrorAction SilentlyContinue)) { throw "git required" }
if (-not (Get-Command python -ErrorAction SilentlyContinue) -and -not (Get-Command py -ErrorAction SilentlyContinue)) {
  Write-Host "Install Python 3.10+ from python.org (Add to PATH), then re-run." -ForegroundColor Red
  exit 1
}
$py = if (Get-Command py -ErrorAction SilentlyContinue) { "py -3" } else { "python" }

if (-not (Test-Path "$HomeDir\.git")) {
  New-Item -ItemType Directory -Force -Path (Split-Path $HomeDir) | Out-Null
  git clone --depth 1 https://github.com/zai-one/codex-mcp.git $HomeDir
} else {
  git -C $HomeDir pull --ff-only
}

Push-Location $HomeDir
Invoke-Expression "$py -m venv .venv"
& .\.venv\Scripts\python.exe -m pip install -U pip
& .\.venv\Scripts\python.exe -m pip install -e ".[test]"

$cfg = Join-Path $env:USERPROFILE ".config\codex-mcp"
New-Item -ItemType Directory -Force -Path $cfg | Out-Null
$envFile = Join-Path $cfg "env.ps1"
@"
# Generated by install.ps1 — no OAuth secrets
`$env:CODEX_APP_MCP_ALLOWED_ROOTS = '$Project'
`$env:CODEX_APP_MCP_ECONOMY = '1'
"@ | Set-Content -Path $envFile -Encoding UTF8

Write-Host "Installed to $HomeDir" -ForegroundColor Green
Write-Host "Env: $envFile"
Write-Host ""
Write-Host "REQUIRED next steps:" -ForegroundColor Yellow
Write-Host "  1) Install Codex CLI and run: codex login"
Write-Host "  2) . $envFile; $HomeDir\.venv\Scripts\python.exe scripts\probe_stdio.py"
Write-Host "  3) Point Claude/Cursor MCP at: $HomeDir\.venv\Scripts\codex-app-mcp.exe"
Pop-Location
